# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-27 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import restaurants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurantlocation_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantlocation',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[restaurants.validators.validation_location]),
        ),
    ]
