# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contants',
            field=models.TextField(help_text='Separated each item by comma'),
        ),
    ]
