# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20180528_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='contants',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
